-- https://kimsereylam.com/sqlite/2020/03/06/full-text-search-with-sqlite.html
CREATE TABLE IF NOT EXISTS comment (reddit_id TEXT UNIQUE NOT NULL,
                                    permalink TEXT,
                                    author TEXT,
                                    subreddit TEXT,
                                    body TEXT,
                                    score INTEGER,
                                    ups INTEGER,
                                    downs INTEGER,
                                    created_utc INTEGER NOT NULL,
                                    retrieved_on INTEGER,
                                    parent_type INTEGER NOT NULL,
                                    parent_id TEXT NOT NULL,
                                    stickied BOOLEAN NOT NULL DEFAULT FALSE,
                                    distinguished TEXT);
