-- decoded_reddit_id is the decoded base36 reddit_id. We use it as our primary key for performance reasons. See more in https://www.sqlite.org/lang_createtable.html#rowid
CREATE TABLE IF NOT EXISTS submission (decoded_reddit_id INTEGER PRIMARY KEY,
                                       reddit_id TEXT NOT NULL,
                                       author TEXT,
                                       author_premium BOOLEAN,
                                       title TEXT NOT NULL,
                                       author_flair_text TEXT,
                                       author_flair_template_id BLOB,
                                       link_flair_template_id BLOB,
                                       link_flair_text TEXT,
                                       subreddit TEXT,
                                       decoded_subreddit_id INTEGER,
                                       subreddit_subscribers INTEGER,
                                       subreddit_type TEXT,
                                       suggested_sort TEXT,
                                       decoded_crosspost_parent_id INTEGER,
                                       post_hint TEXT,
                                       removed_by_category TEXT,
                                       selftext TEXT,
                                       permalink TEXT,
                                       domain TEXT,
                                       url TEXT,
                                       score INTEGER,
                                       ups INTEGER,
                                       downs INTEGER,
                                       created_utc INTEGER NOT NULL,
                                       edited_utc INTEGER,
                                       retrieved_on INTEGER,
                                       is_self BOOLEAN NOT NULL,
                                       over_18 BOOLEAN NOT NULL,
                                       spoiler BOOLEAN,
                                       pinned BOOLEAN,
                                       stickied BOOLEAN NOT NULL,
                                       is_created_from_ads_ui BOOLEAN NOT NULL,
                                       is_gallery BOOLEAN NOT NULL,
                                       is_video BOOLEAN NOT NULL,
                                       is_original_content BOOLEAN,
                                       is_reddit_media_domain BOOLEAN NOT NULL,
                                       quarantine BOOLEAN,
                                       num_comments INTEGER NOT NULL,
                                       contest_mode INTEGER NOT NULL,
                                       num_crossposts INTEGER);